"""
Vision Models.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class VisionResponse(BaseModel):
    """
    Response returned by the Vision Agent.
    """

    success: bool = Field(
        default=True,
        description="Whether the request was successful.",
    )

    message: str = Field(
        default="Image analyzed successfully.",
    )

    analysis: str = Field(
        ...,
        description="Analysis generated by Gemini Vision.",
    )

    errors: list[str] | None = Field(
        default=None,
    )